name: Python Lint
run-name: Linting ${{ github.actor }}'s ${{ github.event_name }} to ${{ github.ref_name }}
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: python -m pip install --upgrade pip pylint
      - name: Lint with pylint
        run: pylint -v *.py
